<?php

use App\Models\User;
use App\Models\Appointment;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\View;
use Illuminate\Support\MessageBag;

require __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

// Share global variables that Middleware usually handles
View::share('errors', new MessageBag());

echo "--- STARTING HEADLESS VERIFICATION: RECEPTIONIST BILLING ---\n";

// 1. Simulate Login
$user = User::where('email', 'receptionist_amy@clinic.com')->first();
if (!$user) {
    die("❌ Error: Receptionist Amy not found.\n");
}
Auth::login($user);
echo "✅ Logged in as: " . $user->name . " (" . $user->role . ")\n";

// 2. Check Dashboard Logic (Controller)
$controller = new \App\Http\Controllers\DashboardController();
// We can't easily capture the return of the controller action without Request, 
// so let's reproduce the query logic to verify the data state.
$readyToBillCount = Appointment::where('status', 'completed')
    ->doesntHave('invoice')
    ->count();

if ($readyToBillCount > 0) {
    echo "✅ Logic Check: Found $readyToBillCount appointment(s) ready to bill.\n";
} else {
    echo "❌ Logic Check: No appointments found ready to bill. Seeding might have failed.\n";
    exit(1);
}

// 3. Check Dashboard View Rendering (UI)
// We render the view manually with the data we expect.
echo "Testing Dashboard View Rendering...\n";

// Re-fetch data needed for dashboard view to avoid 'undefined variable' errors
// This mimics the controller's compact()
$totalPatients = \App\Models\Patient::count();
$totalDoctors = \App\Models\Doctor::count();
$totalAppointments = Appointment::count();
$todayAppointments = Appointment::whereDate('date', now())->count();
$todayRevenue = 0; // Admin only, but view might need it defined or handled
$viewData = [
    'user' => $user,
    'readyToBillCount' => $readyToBillCount,
    'totalPatients' => $totalPatients,
    'todayAppointments' => $todayAppointments,
    'waitingList' => collect([]),
    'triageQueue' => collect([]),
    'recentAppointments' => collect([]), // Mocking required vars
    'totalDoctors' => $totalDoctors,
    'totalAppointments' => $totalAppointments,
    'pending' => 0, 'confirmed' => 0, 'completed' => 0, 'cancelled' => 0,
    'weeklyData' => [],
    'todayRevenue' => 0, 'newPatientsMonth' => 0, 
    'pendingInvoicesCount' => 0, 'pendingInvoicesAmount' => 0,
    'waitingPatients' => 0, 'weekAppointments' => 0, 'monthAppointments' => 0
];

$dashboardHtml = view('dashboard', $viewData)->render();

if (str_contains($dashboardHtml, 'Billing Action Required')) {
    echo "✅ UI Check: 'Billing Action Required' alert is present in HTML.\n";
} else {
    echo "❌ UI Check: Alert NOT found in Dashboard HTML.\n";
}

if (str_contains($dashboardHtml, 'Go to Billing')) {
    echo "✅ UI Check: 'Go to Billing' button is present.\n";
} else {
    echo "❌ UI Check: 'Go to Billing' button NOT found.\n";
}

// 4. Check Appointment Index View (The "Create Invoice" Button)
echo "Testing Appointment Index View Rendering...\n";

// Fetch the specific appointment
$appointment = Appointment::where('status', 'completed')->doesntHave('invoice')->first();
$appointments = new \Illuminate\Pagination\LengthAwarePaginator([$appointment], 1, 15);

$indexHtml = view('appointments.index', [
    'appointments' => $appointments,
    'doctors' => \App\Models\Doctor::all()
])->render();

// We look for the link generated by route('invoices.create-from-appointment', $appointment->id)
// The HTML should contain something like: href="http://localhost/invoices/104/create"
$expectedRoutePart = "invoices/{$appointment->id}/create";

if (str_contains($indexHtml, 'Create Invoice')) {
    echo "✅ UI Check: 'Create Invoice' button text found.\n";
} else {
    echo "❌ UI Check: 'Create Invoice' text NOT found.\n";
}

if (str_contains($indexHtml, $expectedRoutePart)) {
    echo "✅ UI Check: Button contains correct link ($expectedRoutePart).\n";
} else {
    echo "❌ UI Check: Link to create invoice NOT found.\n";
}

echo "--- VERIFICATION COMPLETE ---\n";
